---
title: "**따릉따릉 따릉이**"
subtitle: "⚔<br/>데이터분석을 통한 공영자전거 활성화 방안"
author: "이다연  김채원"
output:
  xaringan::moon_reader:
    lib_dir: libs
    css: ["dsXaringan.css", middlebury]
    nature:
      highlightStyle: github
      highlightLines: true
---
```{r include=FALSE}
library(dplyr)
library(plyr)
library(stringr)
library(chron)
library(readr)
library(tidyverse)
```

## 목차
<br/>
###1. 분석 배경 

###2. 분석 시행
####1. 구별 이용량
####2. 일별 이용량
 
###3.결론 및 제안

---
class: inverse, center, middle

# 1. 분석 배경


---
###공영자전거 배치의 불균형 해소
###공영자전거 시스템의 확대 방향
---
class: inverse, center, middle

# 2. 분석 시행
###구별 이용량 예측
---
###구별 이용량 예측 - <span style="font-size: 30px;color:grey">DATA</span>


1)대여이력 정보 데이터
```{r message=FALSE, warning=FALSE, include=FALSE, paged.print=FALSE}
Sys.setlocale("LC_ALL","korean")
```
```{r echo=TRUE, message=FALSE, warning=FALSE, paged.print=FALSE}

rentinfo<-read_csv("2018년 따릉이 이용.csv",
                   locale=locale(encoding="euc-kr"))
rentinfo <- rentinfo[,-1]
```
```{r echo=FALSE, message=FALSE, warning=FALSE, paged.print=FALSE, tidy=FALSE}
DT::datatable(
  head(rentinfo[-c(2,4,6,7,8,9)], 10),
  fillContainer = FALSE, options = list(autoWidth=TRUE, pageLength = 4,scrollX = TRUE,
  scrollCollapse = TRUE)
)
```

---
###구별 이용량 예측 - <span style="font-size: 30px;color:grey">DATA</span>

2) 대여소 위치 정보 데이터
```{r echo=TRUE, message=FALSE, warning=FALSE, paged.print=FALSE}
rentloc <- read.csv("서울특별시 공공자전거 대여소 정보.csv")
names(rentloc)<-c('구명',	'대여소ID'	,'대여소번호'	,'대여소명',
                  '대여소 주소',	'거치대수',	'위도'	,'경도')
```

```{r echo=FALSE, message=FALSE, warning=FALSE, paged.print=FALSE, tidy=FALSE}
DT::datatable(
  head(rentloc[,-c(2,4,7,8,9)], 10),
  fillContainer = FALSE, options = list(autoWidth=TRUE, pageLength = 4,scrollX = TRUE,
  scrollCollapse = TRUE)
)
```

---
###구별 이용량 예측 - <span style="font-size: 30px;color:grey">DATA</span>

<span style="color:#587a8f">대여소번호</span>를 참조해 정류장이 있는 구를 새로운 변수로 지정
```{r echo=TRUE, message=FALSE, warning=FALSE, paged.print=FALSE}
rentloc$대여소번호 <- as.factor(rentloc$대여소번호)
rentinfo$대여대여소번호 <- as.factor(rentinfo$대여대여소번호)
rent<-left_join(rentinfo, rentloc[,c(1,3)],
                by=c("대여대여소번호"="대여소번호"))
#대여소 번호가 없는 경우 NA로 변환
```

구별 대여소 이용량 계산
```{r}
# 대여소 번호별 이용량
before<-rentinfo %>% summarise(count(대여대여소번호))
before<- before$`count(대여대여소번호`
names(before) <- c("대여대여소번호", "이용량")
```

```{r message=FALSE, warning=FALSE, include=FALSE, paged.print=FALSE}
rent_gu<-left_join(before,rentloc[,c(1,3)],
                   by=c("대여대여소번호"='대여소번호'))
rent_gu[is.na(rent_gu$구명),]
head(rent_gu,3)
```

```{r}
#구별 대여소 이용량
rentUse_gu<- rent_gu %>%na.omit()%>% group_by(`구명`)%>%dplyr::summarise(이용량=sum(이용량))  
```

---
###구별 이용량 예측 - <span style="font-size: 30px;color:grey">DATA</span>

가공된 구별 이용량 데이터
```{r message=FALSE, warning=FALSE, include=FALSE, paged.print=FALSE}
names(rentUse_gu)<-c("구", "이용량")
#최종데이터: rentUse_gu
```
```{r}
head(rentUse_gu)
```
---
###구별 이용량 예측 - <span style="font-size: 30px;color:grey">EDA</span>
 - 구별 이용량
 
 
```{r echo=FALSE, message=FALSE, warning=FALSE, paged.print=FALSE}
#구별 이용량 plot
ggplot(data=rentUse_gu %>% arrange(구), aes(x=구, y= 이용량))+ geom_col()
```
---
###구별 이용량 예측 - <span style="font-size: 30px;color:grey">EDA</span>
 - 구별 대여소 수
 
```{r echo=FALSE, message=FALSE, warning=FALSE, paged.print=FALSE}

#구별 대여소 수 plot
gu_rentshop<-rent_gu %>% group_by(구명) %>% dplyr::count(name="대여소수") %>% arrange(구명)%>% na.omit()
ggplot(data=gu_rentshop, aes(x=구명, y= 대여소수))+geom_col()
```
